/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package texteditor;

/**
 *
 * @author jmielec
 */
public class TextEditorGUI extends javax.swing.JFrame {

    /**
     * Creates new form TextEditor
     */
    public TextEditorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        New = new javax.swing.JMenuItem();
        Open = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();
        SaveAs = new javax.swing.JMenuItem();
        AutosaveToggle = new javax.swing.JCheckBoxMenuItem();
        Print = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();
        Undo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Cut = new javax.swing.JMenuItem();
        Copy = new javax.swing.JMenuItem();
        Paste = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Find = new javax.swing.JMenuItem();
        Replace = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        SelectAll = new javax.swing.JMenuItem();
        DesignMenu = new javax.swing.JMenu();
        Font = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        FontSize = new javax.swing.JMenu();
        FontColor = new javax.swing.JMenu();
        BackgroundColor = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        Heading = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        Bold = new javax.swing.JMenuItem();
        Italics = new javax.swing.JMenuItem();
        Underline = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        Highlight = new javax.swing.JMenuItem();
        HighlightColor = new javax.swing.JMenu();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        BulletedList = new javax.swing.JMenuItem();
        NumberedList = new javax.swing.JMenuItem();
        Layout = new javax.swing.JMenu();
        Margins = new javax.swing.JMenuItem();
        Columns = new javax.swing.JMenuItem();
        Spacing = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenu();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Text Editor Extrodinaire");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 1100));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenuBar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        FileMenu.setText("File");
        FileMenu.setToolTipText("");

        New.setText("New");
        FileMenu.add(New);

        Open.setText("Open");
        FileMenu.add(Open);

        Save.setText("Save");
        FileMenu.add(Save);

        SaveAs.setText("Save As");
        FileMenu.add(SaveAs);

        AutosaveToggle.setSelected(true);
        AutosaveToggle.setText("Autosave");
        FileMenu.add(AutosaveToggle);

        Print.setText("Print");
        FileMenu.add(Print);

        jMenuBar.add(FileMenu);

        EditMenu.setText("Edit");

        Undo.setText("Undo");
        EditMenu.add(Undo);
        EditMenu.add(jSeparator1);

        Cut.setText("Cut");
        EditMenu.add(Cut);

        Copy.setText("Copy");
        Copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyActionPerformed(evt);
            }
        });
        EditMenu.add(Copy);

        Paste.setText("Paste");
        EditMenu.add(Paste);
        EditMenu.add(jSeparator2);

        Find.setText("Find");
        EditMenu.add(Find);

        Replace.setText("Replace");
        EditMenu.add(Replace);
        EditMenu.add(jSeparator3);

        SelectAll.setText("Select All");
        EditMenu.add(SelectAll);

        jMenuBar.add(EditMenu);

        DesignMenu.setText("Design");

        Font.setText("Font");

        jMenuItem8.setText("jMenuItem8");
        Font.add(jMenuItem8);

        jMenuItem9.setText("jMenuItem9");
        Font.add(jMenuItem9);

        jMenuItem10.setText("jMenuItem10");
        Font.add(jMenuItem10);

        jMenuItem11.setText("jMenuItem11");
        Font.add(jMenuItem11);

        DesignMenu.add(Font);

        FontSize.setText("Font Size");
        DesignMenu.add(FontSize);

        FontColor.setText("Font Color");
        DesignMenu.add(FontColor);

        BackgroundColor.setText("Background Color");
        DesignMenu.add(BackgroundColor);
        DesignMenu.add(jSeparator4);

        Heading.setText("Heading");
        DesignMenu.add(Heading);
        DesignMenu.add(jSeparator7);

        Bold.setText("Bold");
        DesignMenu.add(Bold);

        Italics.setText("Italics");
        Italics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItalicsActionPerformed(evt);
            }
        });
        DesignMenu.add(Italics);

        Underline.setText("Underline");
        DesignMenu.add(Underline);
        DesignMenu.add(jSeparator5);

        Highlight.setText("Highlight");
        DesignMenu.add(Highlight);

        HighlightColor.setText("Highlight Color");
        DesignMenu.add(HighlightColor);
        DesignMenu.add(jSeparator6);

        BulletedList.setText("Bulleted List");
        DesignMenu.add(BulletedList);

        NumberedList.setText("Numbered List");
        DesignMenu.add(NumberedList);

        jMenuBar.add(DesignMenu);

        Layout.setText("Layout");

        Margins.setText("Margins");
        Margins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarginsActionPerformed(evt);
            }
        });
        Layout.add(Margins);

        Columns.setText("Columns");
        Layout.add(Columns);

        Spacing.setText("Spacing");
        Layout.add(Spacing);

        jMenuBar.add(Layout);

        Exit.setText("Close");
        jMenuBar.add(Exit);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CopyActionPerformed

    private void ItalicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItalicsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItalicsActionPerformed

    private void MarginsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarginsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarginsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextEditorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextEditorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextEditorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextEditorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextEditorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem AutosaveToggle;
    private javax.swing.JMenu BackgroundColor;
    private javax.swing.JMenuItem Bold;
    private javax.swing.JMenuItem BulletedList;
    private javax.swing.JMenuItem Columns;
    private javax.swing.JMenuItem Copy;
    private javax.swing.JMenuItem Cut;
    private javax.swing.JMenu DesignMenu;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenu Exit;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem Find;
    private javax.swing.JMenu Font;
    private javax.swing.JMenu FontColor;
    private javax.swing.JMenu FontSize;
    private javax.swing.JMenuItem Heading;
    private javax.swing.JMenuItem Highlight;
    private javax.swing.JMenu HighlightColor;
    private javax.swing.JMenuItem Italics;
    private javax.swing.JMenu Layout;
    private javax.swing.JMenuItem Margins;
    private javax.swing.JMenuItem New;
    private javax.swing.JMenuItem NumberedList;
    private javax.swing.JMenuItem Open;
    private javax.swing.JMenuItem Paste;
    private javax.swing.JMenuItem Print;
    private javax.swing.JMenuItem Replace;
    private javax.swing.JMenuItem Save;
    private javax.swing.JMenuItem SaveAs;
    private javax.swing.JMenuItem SelectAll;
    private javax.swing.JMenuItem Spacing;
    private javax.swing.JMenuItem Underline;
    private javax.swing.JMenuItem Undo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
