/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package texteditorgui2;

import java.awt.Color;
import java.io.File;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JToggleButton;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;


/**
 *
 * @author dylanmora
 */
public class TextEditorGUI extends javax.swing.JFrame implements ActionListener, DocumentListener, WindowListener {
    Color color = Color.BLACK;
    private String fName = "Arial" ;
    private int fStyle = 2;
    private int fSize= 40 ;
    private boolean dirty;
    /**
     * Creates new form TextEditorGUI
     */
    public TextEditorGUI() {
        initComponents();
        clearBttm.addActionListener(this);
        editableBttm.addActionListener(this);
        colorChooserBttm.addActionListener(this);
        fontNameScroll.addActionListener(this);
        fontSizeScroll.addActionListener(this);
        fontStyleScroll.addActionListener(this);
        addBttm.addActionListener(this);
        saveBttm.addActionListener(this);
        txtDoc.getDocument().addDocumentListener(this);
        addWindowListener(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        topPanel = new javax.swing.JPanel();
        topBarPanel = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        addBttm = new javax.swing.JButton();
        saveBttm = new javax.swing.JButton();
        printBttm = new javax.swing.JButton();
        topTabbedPanel = new javax.swing.JTabbedPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        modesBttm = new javax.swing.JToggleButton();
        fontNameScroll = new javax.swing.JComboBox<>();
        fontSizeScroll = new javax.swing.JComboBox<>();
        fontStyleScroll = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        colorChooserBttm = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        editableBttm = new javax.swing.JToggleButton();
        shareBttm = new javax.swing.JButton();
        clearBttm = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JSeparator();
        shapeLabel = new javax.swing.JLayeredPane();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        uploadLabel = new javax.swing.JLabel();
        emojiLabel = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        picLabel = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jButton11 = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JSeparator();
        pageNLabel = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDoc = new javax.swing.JTextArea();
        lowPanel = new javax.swing.JPanel();
        wordLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Text Editor");

        topPanel.setBackground(new java.awt.Color(204, 204, 204));
        topPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        topPanel.setMaximumSize(new java.awt.Dimension(32767, 35767));
        topPanel.setPreferredSize(new java.awt.Dimension(918, 130));

        topBarPanel.setBackground(new java.awt.Color(204, 204, 204));
        topBarPanel.setBorder(null);
        topBarPanel.setRollover(true);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("  ");
        topBarPanel.add(jLabel1);

        addBttm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditorgui2/add_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        addBttm.setFocusable(false);
        addBttm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addBttm.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addBttm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBttmActionPerformed(evt);
            }
        });
        topBarPanel.add(addBttm);

        saveBttm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditorgui2/save_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        saveBttm.setFocusable(false);
        saveBttm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveBttm.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveBttm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBttmActionPerformed(evt);
            }
        });
        topBarPanel.add(saveBttm);

        printBttm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditorgui2/print_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        printBttm.setFocusable(false);
        printBttm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        printBttm.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        topBarPanel.add(printBttm);

        topTabbedPanel.setBackground(new java.awt.Color(255, 255, 255));
        topTabbedPanel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        jLayeredPane2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane2.setForeground(new java.awt.Color(255, 255, 255));
        jLayeredPane2.setPreferredSize(new java.awt.Dimension(1022, 80));

        modesBttm.setBackground(new java.awt.Color(242, 242, 242));
        modesBttm.setForeground(new java.awt.Color(255, 255, 255));
        modesBttm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditorgui2/dark_mode_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        modesBttm.setBorder(null);
        modesBttm.setContentAreaFilled(false);
        modesBttm.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditorgui2/light_mode_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        modesBttm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modesBttmActionPerformed(evt);
            }
        });

        fontNameScroll.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        fontNameScroll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arial", "Helvetica Neue", ".AppleSystemUIFont", "Zapfino" }));
        fontNameScroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontNameScrollActionPerformed(evt);
            }
        });

        fontSizeScroll.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        fontSizeScroll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "24", "36", "46", "60" }));

        fontStyleScroll.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        fontStyleScroll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Style", "Bold", "Italic", "Bold & Italic" }));
        fontStyleScroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontStyleScrollActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        colorChooserBttm.setBackground(new java.awt.Color(0, 0, 0));
        colorChooserBttm.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        colorChooserBttm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditorgui2/format_ink_highlighter_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        colorChooserBttm.setText("Font Color");
        colorChooserBttm.setBorder(null);
        colorChooserBttm.setBorderPainted(false);
        colorChooserBttm.setContentAreaFilled(false);

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setToolTipText("");

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        editableBttm.setSelected(true);
        editableBttm.setText("Read Only");

        shareBttm.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        shareBttm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditorgui2/share_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        shareBttm.setText("Share");
        shareBttm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shareBttmActionPerformed(evt);
            }
        });

        clearBttm.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        clearBttm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditorgui2/auto_delete_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        clearBttm.setText("Clear");
        clearBttm.setToolTipText("");

        jSeparator13.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator13.setToolTipText("");

        jLayeredPane2.setLayer(modesBttm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(fontNameScroll, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(fontSizeScroll, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(fontStyleScroll, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(colorChooserBttm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jSeparator6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jSeparator7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(editableBttm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(shareBttm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(clearBttm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jSeparator13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(modesBttm, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fontNameScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fontSizeScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fontStyleScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorChooserBttm, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editableBttm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(shareBttm)
                .addGap(20, 20, 20)
                .addComponent(clearBttm)
                .addGap(30, 30, 30))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fontStyleScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(colorChooserBttm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fontNameScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fontSizeScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(modesBttm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editableBttm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(shareBttm)
                        .addComponent(clearBttm)))
                .addGap(26, 26, 26))
        );

        topTabbedPanel.addTab("Home", jLayeredPane2);

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditorgui2/play_shapes_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton7.setBorder(null);

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditorgui2/emoticon_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton8.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Shapes");

        uploadLabel.setFont(new java.awt.Font("Helvetica", 0, 15)); // NOI18N
        uploadLabel.setForeground(new java.awt.Color(102, 102, 102));
        uploadLabel.setText("Upload");

        emojiLabel.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        emojiLabel.setForeground(new java.awt.Color(102, 102, 102));
        emojiLabel.setText("Emojis");

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton9.setText("#");
        jButton9.setBorder(null);

        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditorgui2/upload_file_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton10.setBorder(null);

        picLabel.setFont(new java.awt.Font("Helvetica", 0, 15)); // NOI18N
        picLabel.setForeground(new java.awt.Color(102, 102, 102));
        picLabel.setText("Pictures");

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator8.setToolTipText("");

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator9.setToolTipText("");

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator10.setToolTipText("");

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditorgui2/image_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setPreferredSize(new java.awt.Dimension(50, 34));
        jButton11.setSize(new java.awt.Dimension(50, 34));

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator11.setToolTipText("");

        pageNLabel.setFont(new java.awt.Font("Helvetica", 0, 15)); // NOI18N
        pageNLabel.setForeground(new java.awt.Color(102, 102, 102));
        pageNLabel.setText("Page Number");

        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator12.setToolTipText("");

        shapeLabel.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        shapeLabel.setLayer(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        shapeLabel.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        shapeLabel.setLayer(uploadLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        shapeLabel.setLayer(emojiLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        shapeLabel.setLayer(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        shapeLabel.setLayer(jButton10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        shapeLabel.setLayer(picLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        shapeLabel.setLayer(jSeparator8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        shapeLabel.setLayer(jSeparator9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        shapeLabel.setLayer(jSeparator10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        shapeLabel.setLayer(jButton11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        shapeLabel.setLayer(jSeparator11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        shapeLabel.setLayer(pageNLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        shapeLabel.setLayer(jSeparator12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout shapeLabelLayout = new javax.swing.GroupLayout(shapeLabel);
        shapeLabel.setLayout(shapeLabelLayout);
        shapeLabelLayout.setHorizontalGroup(
            shapeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shapeLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(shapeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(picLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(shapeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shapeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emojiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shapeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uploadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shapeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pageNLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(628, Short.MAX_VALUE))
        );
        shapeLabelLayout.setVerticalGroup(
            shapeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapeLabelLayout.createSequentialGroup()
                .addGroup(shapeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator10)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(shapeLabelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(shapeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(shapeLabelLayout.createSequentialGroup()
                                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pageNLabel))
                            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, shapeLabelLayout.createSequentialGroup()
                                .addGroup(shapeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, shapeLabelLayout.createSequentialGroup()
                                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(picLabel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, shapeLabelLayout.createSequentialGroup()
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(emojiLabel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, shapeLabelLayout.createSequentialGroup()
                                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(uploadLabel)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(shapeLabelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))))
                .addContainerGap())
        );

        topTabbedPanel.addTab("Insert", shapeLabel);

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topBarPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addComponent(topTabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(topBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(topTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setBorder(null);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(100, 150));

        txtDoc.setColumns(20);
        txtDoc.setRows(5);
        jScrollPane2.setViewportView(txtDoc);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        lowPanel.setBackground(new java.awt.Color(204, 204, 204));
        lowPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lowPanel.setPreferredSize(new java.awt.Dimension(923, 40));

        wordLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        wordLabel.setText("0 words");

        javax.swing.GroupLayout lowPanelLayout = new javax.swing.GroupLayout(lowPanel);
        lowPanel.setLayout(lowPanelLayout);
        lowPanelLayout.setHorizontalGroup(
            lowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                .addComponent(wordLabel)
                .addGap(68, 68, 68))
        );
        lowPanelLayout.setVerticalGroup(
            lowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lowPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(lowPanelLayout.createSequentialGroup()
                        .addComponent(wordLabel)
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(lowPanel, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(1024, 688));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fontStyleScrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontStyleScrollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fontStyleScrollActionPerformed

    private void modesBttmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modesBttmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modesBttmActionPerformed

    private void fontNameScrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontNameScrollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fontNameScrollActionPerformed

    private void addBttmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBttmActionPerformed
        
    }//GEN-LAST:event_addBttmActionPerformed

    private void saveBttmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBttmActionPerformed
        
    }//GEN-LAST:event_saveBttmActionPerformed

    private void shareBttmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shareBttmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shareBttmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextEditorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextEditorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextEditorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextEditorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextEditorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBttm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton clearBttm;
    private javax.swing.JButton colorChooserBttm;
    private javax.swing.JToggleButton editableBttm;
    private javax.swing.JLabel emojiLabel;
    private javax.swing.JComboBox<String> fontNameScroll;
    private javax.swing.JComboBox<String> fontSizeScroll;
    private javax.swing.JComboBox<String> fontStyleScroll;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JPanel lowPanel;
    private javax.swing.JToggleButton modesBttm;
    private javax.swing.JLabel pageNLabel;
    private javax.swing.JLabel picLabel;
    private javax.swing.JButton printBttm;
    private javax.swing.JButton saveBttm;
    private javax.swing.JLayeredPane shapeLabel;
    private javax.swing.JButton shareBttm;
    private javax.swing.JLabel statusLabel;
    public javax.swing.JToolBar topBarPanel;
    protected javax.swing.JPanel topPanel;
    protected javax.swing.JTabbedPane topTabbedPanel;
    private javax.swing.JTextArea txtDoc;
    private javax.swing.JLabel uploadLabel;
    private javax.swing.JLabel wordLabel;
    // End of variables declaration//GEN-END:variables

//Arrays of swinng, for each loop.
    JPanel[] panelArray = {topPanel, lowPanel};
    JToggleButton[] tButtonArray={modesBttm};
    JButton[] buttonArray = {addBttm,clearBttm,jButton10,jButton11,colorChooserBttm,jButton7,jButton8,jButton9,printBttm,saveBttm,shareBttm};
    JSeparator[] separatorArray={jSeparator1,jSeparator10,jSeparator11,jSeparator12,jSeparator4,jSeparator6,jSeparator7,jSeparator8,jSeparator9};
    JLabel[] labelArray={emojiLabel,jLabel1,jLabel3,pageNLabel,picLabel,uploadLabel,wordLabel};    
    
  
    
    @Override
    public void actionPerformed(ActionEvent ae) {
       //Clear all Buttom
        if(ae.getSource()==clearBttm){
            int tt = JOptionPane.showOptionDialog(this, "It will delete everything, \n Are you sure?", "Clear all", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, new String[]{"Continue","Discard"}, "Continue");
                if(tt==0){
                    txtDoc.setText("");
                }
        }
        
        //Edit and Read Only
        if(ae.getSource()==editableBttm){
            boolean isSelected = editableBttm.isSelected();
            txtDoc.setEditable(isSelected); 
        }
        
        //Color Chooser
        if(ae.getSource()==colorChooserBttm) {
            color = JColorChooser.showDialog(this,"Choose a Color", color);
            txtDoc.setForeground(color);
        }
        
         //Font Name
        if(ae.getSource()==fontNameScroll) {
            String selectedFontName = (String) fontNameScroll.getSelectedItem();
            fName = selectedFontName;
             Font font = new Font(fName,fStyle,fSize);
             txtDoc.setFont(font);
        }
        
        //Font Size
        if(ae.getSource()== fontSizeScroll){
            String selectedFontSizeString = (String) fontSizeScroll.getSelectedItem();
            int selectedFontSize = Integer.parseInt(selectedFontSizeString);
            fSize = selectedFontSize;
            Font font = new Font(fName,fStyle,fSize);
            txtDoc.setFont(font);
        }
        
        //Font Style
        if(ae.getSource()== fontStyleScroll){
            String selectedFontStyleString = (String) fontStyleScroll.getSelectedItem();
            switch(selectedFontStyleString){
                case "Bold" -> {
                    fStyle = 1;
                }
                case "Italic" -> {
                    fStyle = 2;
                }
                case "Bold & Italic" -> {
                    fStyle = 3;
                }
                default -> {
                    fStyle = 0;
                }
            }
            Font font = new Font(fName,fStyle,fSize);
            txtDoc.setFont(font);
        }
        
        if(ae.getSource()==saveBttm){
            if(dirty){
                saveFile();
          
            } else {
                JOptionPane.showMessageDialog(this, "No changes have been made.");
            }
        }
        
        if(ae.getSource()== addBttm){
            if(dirty){
                saveFile();
            }
            newFile();
        } 
     
    }
    public void newFile(){
        java.awt.Toolkit.getDefaultToolkit().beep();
        int newValue = JOptionPane.showOptionDialog(this, "Open new document. \nLeave this document. ", "New Document?", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, new String[]{"Open","Stay"}, "Create");
        
        if(newValue == 0){
            File newDoc = new File("filename.txt");
            txtDoc.setText("");
            try {
                if (newDoc.createNewFile()) {
                    System.out.println("File created: " + newDoc.getName());
                } else {
                    System.out.println("File already exists.");
                }
            } catch (IOException e) {
                System.out.println("An error occurred.");
            }
        }
    }
    public void saveFile(){
        java.awt.Toolkit.getDefaultToolkit().beep();
        int retValue = JOptionPane.showOptionDialog(this, "Document has changed. Save it?", "Save Changes?", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, new String[]{"Save","Discard"}, "Save");
        if(retValue == 0){
            try{
                File f;
                JFileChooser chooser = new JFileChooser();
                int saveValue = chooser.showSaveDialog(this);
                if(saveValue == JFileChooser.APPROVE_OPTION){
                    f = chooser.getSelectedFile();
                }else{
                    return;
                }
                BufferedReader reader = new BufferedReader(new StringReader(txtDoc.getText()));
                BufferedWriter writer = new BufferedWriter(new FileWriter(f));
                String str;
                while((str = reader.readLine()) != null){
                    writer.write(str + System.getProperty("line.separator"));
                }
                
                writer.flush();
                reader.close();
                writer.close();
                statusLabel.setText("Saved " + chooser.getSelectedFile().getAbsolutePath());
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Unable to save file");
            }
        }
    }

    @Override
    public void insertUpdate(DocumentEvent e) {
        dirty = true;
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        dirty = true;
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        //plain text components don't fire this event
    }

    @Override
    public void windowOpened(WindowEvent e) {
        
    }

    @Override
    public void windowClosing(WindowEvent e) {
        if(dirty)
            saveFile();
    }

    @Override
    public void windowClosed(WindowEvent e) {
        
    }

    @Override
    public void windowIconified(WindowEvent e) {
        
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        
    }

    @Override
    public void windowActivated(WindowEvent e) {
        
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        
    }
}
